// react-xm/src/views/register/register.jsx
import React, { Component } from 'react'
import {registers} from '../../api/api'
import {Toast} from 'antd-mobile'
export default class register extends Component {
  state={
    userName:"",
    password:"",
    realName:""
  }
  changeFun(e){
    this.setState({[e.target.name]:e.target.value})
  }
  async clicks(){
    let {userName,password,realName}=this.state
   
    try{
       let res=await registers({userName,password,realName})
      if(res.data.code){
        this.props.history.push("/login");
      }
    }catch(e){
      //console.log(e.response.data);
      Toast.info(e.response.data.message, 2)
    }
   
   
  }
  render() {
    let {userName,password,realName}=this.state
    return <div>
          <li>用户名<input type="text" value={userName} name="userName" onChange={(e)=>this.changeFun(e)}/></li>
          <li>密码<input type="password" value={password} name="password" onChange={(e)=>this.changeFun(e)}/></li>
          <li>姓名<input type="text" value={realName} name="realName" onChange={(e)=>this.changeFun(e)}/></li>
          <button onClick={()=>this.clicks()}>注册</button>
      </div>
  }
}

// vuexy/src/views/register/register.vue
<template>
    <div class="register">
        <ul class="register-ul">
            <h3>注册</h3>
            <li><input type="text" placeholder="用户名" v-model="phone"></li>
            <li><input type="password" placeholder="密码" v-model="pwd"></li>
            <li><button @click="clicks">注册</button></li>
        </ul>
    </div>
</template>

<script>
import {register} from '@/api/api'
export default {
    name:'register',
    data(){
        return {
            phone:"",
            pwd:""
        }
    },
    methods:{
        async clicks(){
            try {
                const res=await register({phone:this.phone,password:this.pwd})
                // console.log(res); 
                if(res.data.code==1){
                    this.$router.go(-1)
                }
            } catch (e) {
               if(e.response.data.code==0){
                   alert(e.response.data.msg)
               } 
            }
           
        }
    }
}
</script>

<style>
    .register-ul{
        margin: 0 auto;
    }
    input{
        width: 300px;
        height: 25px;
        margin-top: 15px;
    }
    button{
        height: 35px;
        width: 300px;
        margin-top: 15px;
        border-radius: 15px;
        border: 0;
        color:#fff;
        background: red;
        outline: none;
    }
</style>
